export const SITE_NAME = 'SaveFromPro';
export const SITE_DESCRIPTION = 'Free online video downloader. Download videos from Facebook, Instagram, TikTok, Twitter/X, and 8 more platforms in HD quality.';
export const SITE_URL = 'https://savefrompro.com';

export const PLATFORMS = [
  {
    slug: 'facebook',
    name: 'Facebook',
    icon: 'facebook',
    color: '#1877F2',
    gradient: 'from-[#1877F2] to-[#0a5dc2]',
    baseUrl: 'https://facebook.com',
    description: 'Download Facebook videos, reels, and stories in HD quality. Fast, free, and no login required.',
    features: ['Videos', 'Reels', 'Stories', 'HD Quality'],
    urlPattern: /(?:https?:\/\/)?(?:www\.|m\.|web\.)?(?:facebook\.com|fb\.watch|fb\.com)/i,
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    icon: 'instagram',
    color: '#E4405F',
    gradient: 'from-[#E4405F] via-[#FD1D1D] to-[#F77737]',
    baseUrl: 'https://instagram.com',
    description: 'Download Instagram reels, posts, stories, and IGTV videos. Save any Instagram content easily.',
    features: ['Reels', 'Posts', 'Stories', 'IGTV'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?instagram\.com/i,
  },
  {
    slug: 'tiktok',
    name: 'TikTok',
    icon: 'music',
    color: '#000000',
    gradient: 'from-[#00f2ea] to-[#ff0050]',
    baseUrl: 'https://tiktok.com',
    description: 'Download TikTok videos without watermark in HD. Save TikTok content for offline viewing.',
    features: ['No Watermark', 'HD Videos', 'MP3 Audio', 'Fast'],
    urlPattern: /(?:https?:\/\/)?(?:www\.|vm\.)?tiktok\.com/i,
  },
  {
    slug: 'twitter',
    name: 'Twitter / X',
    icon: 'twitter',
    color: '#000000',
    gradient: 'from-[#1DA1F2] to-[#0d8bd9]',
    baseUrl: 'https://x.com',
    description: 'Download Twitter/X videos and GIFs from tweets. Save any media from X posts instantly.',
    features: ['Videos', 'GIFs', 'HD Quality', 'Fast'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?(?:twitter\.com|x\.com)/i,
  },
  {
    slug: 'snapchat',
    name: 'Snapchat',
    icon: 'ghost',
    color: '#FFFC00',
    gradient: 'from-[#FFFC00] to-[#e6e300]',
    baseUrl: 'https://snapchat.com',
    description: 'Download Snapchat Spotlight videos and public stories. Save snaps before they disappear.',
    features: ['Spotlight', 'Stories', 'HD Videos', 'Fast'],
    urlPattern: /(?:https?:\/\/)?(?:www\.|story\.)?snapchat\.com/i,
  },
  {
    slug: 'twitch',
    name: 'Twitch',
    icon: 'twitch',
    color: '#9146FF',
    gradient: 'from-[#9146FF] to-[#772ce8]',
    baseUrl: 'https://twitch.tv',
    description: 'Download Twitch clips and VODs. Save your favorite streaming moments offline.',
    features: ['Clips', 'VODs', 'HD Quality', 'Fast'],
    urlPattern: /(?:https?:\/\/)?(?:www\.|clips\.)?twitch\.tv/i,
  },
  {
    slug: 'dailymotion',
    name: 'Dailymotion',
    icon: 'play',
    color: '#00AAFF',
    gradient: 'from-[#00AAFF] to-[#0088cc]',
    baseUrl: 'https://dailymotion.com',
    description: 'Download Dailymotion videos in multiple qualities. Fast and free video downloader.',
    features: ['Videos', 'Multiple Quality', 'Fast', 'Free'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?(?:dailymotion\.com|dai\.ly)/i,
  },
  {
    slug: 'vimeo',
    name: 'Vimeo',
    icon: 'video',
    color: '#1AB7EA',
    gradient: 'from-[#1AB7EA] to-[#162221]',
    baseUrl: 'https://vimeo.com',
    description: 'Download Vimeo videos in HD, Full HD, and 4K quality. Professional video downloads.',
    features: ['HD', 'Full HD', '4K', 'Fast'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?vimeo\.com/i,
  },
  {
    slug: 'reddit',
    name: 'Reddit',
    icon: 'message-circle',
    color: '#FF4500',
    gradient: 'from-[#FF4500] to-[#cc3700]',
    baseUrl: 'https://reddit.com',
    description: 'Download Reddit videos with audio merged. Save any Reddit video or GIF post.',
    features: ['Videos', 'GIFs', 'Audio Merged', 'HD'],
    urlPattern: /(?:https?:\/\/)?(?:www\.|old\.)?(?:reddit\.com|redd\.it)/i,
  },
  {
    slug: 'threads',
    name: 'Threads',
    icon: 'at-sign',
    color: '#000000',
    gradient: 'from-[#000000] to-[#333333]',
    baseUrl: 'https://threads.net',
    description: 'Download Threads videos and images. Save content from Meta Threads app.',
    features: ['Videos', 'Images', 'Fast', 'Free'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?threads\.net/i,
  },
  {
    slug: 'linkedin',
    name: 'LinkedIn',
    icon: 'linkedin',
    color: '#0A66C2',
    gradient: 'from-[#0A66C2] to-[#004182]',
    baseUrl: 'https://linkedin.com',
    description: 'Download LinkedIn videos from posts. Save professional content for offline viewing.',
    features: ['Videos', 'HD Quality', 'Fast', 'Free'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?linkedin\.com/i,
  },
  {
    slug: 'pinterest',
    name: 'Pinterest',
    icon: 'pin',
    color: '#E60023',
    gradient: 'from-[#E60023] to-[#ad001a]',
    baseUrl: 'https://pinterest.com',
    description: 'Download Pinterest images and video pins in high resolution. Save pins easily.',
    features: ['Images', 'Video Pins', 'High Res', 'Fast'],
    urlPattern: /(?:https?:\/\/)?(?:www\.)?(?:pinterest\.[a-z.]+|pin\.it)/i,
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: 1,
    title: 'Paste the URL',
    description: 'Copy the video URL from any supported platform and paste it in the input field above.',
    icon: 'clipboard-paste',
  },
  {
    step: 2,
    title: 'Fetch Media Info',
    description: 'Click the download button and we will fetch the video details including quality options.',
    icon: 'search',
  },
  {
    step: 3,
    title: 'Download & Enjoy',
    description: 'Select your preferred quality and download the video to your device. It is that simple!',
    icon: 'download',
  },
];

export const FEATURES = [
  {
    title: 'Completely Free',
    description: 'No hidden charges, no premium plans. Download unlimited videos for free.',
    icon: 'badge-dollar-sign',
  },
  {
    title: 'HD Quality',
    description: 'Download videos in the highest quality available — HD, Full HD, and even 4K.',
    icon: 'monitor',
  },
  {
    title: 'No Registration',
    description: 'No signup, no login, no personal data required. Just paste and download.',
    icon: 'user-x',
  },
  {
    title: 'Lightning Fast',
    description: 'Powered by Cloudflare Edge network for the fastest downloads worldwide.',
    icon: 'zap',
  },
  {
    title: '12+ Platforms',
    description: 'Support for Facebook, Instagram, TikTok, Twitter/X, and 8 more platforms.',
    icon: 'layout-grid',
  },
  {
    title: 'Mobile Friendly',
    description: 'Works perfectly on any device — phone, tablet, or desktop. No app needed.',
    icon: 'smartphone',
  },
];

export const GLOBAL_FAQS = [
  {
    question: 'Is SaveFromPro really free?',
    answer: 'Yes! SaveFromPro is 100% free to use. There are no hidden charges, no premium plans, and no limits on downloads.',
  },
  {
    question: 'Do I need to install any software?',
    answer: 'No! SaveFromPro works entirely in your browser. No app, extension, or software installation is required.',
  },
  {
    question: 'Is it safe to use SaveFromPro?',
    answer: 'Absolutely. We do not store any personal data or downloaded files. Your privacy is our priority.',
  },
  {
    question: 'What video quality can I download?',
    answer: 'We offer the highest quality available from the source — including HD (720p), Full HD (1080p), and sometimes 4K depending on the platform.',
  },
  {
    question: 'Which platforms are supported?',
    answer: 'We support Facebook, Instagram, TikTok, Twitter/X, Snapchat, Twitch, Dailymotion, Vimeo, Reddit, Threads, LinkedIn, and Pinterest.',
  },
  {
    question: 'Can I download videos on my phone?',
    answer: 'Yes! SaveFromPro works on all devices including Android, iPhone, iPad, and desktop browsers.',
  },
];
